# Generated by Django 2.2.7 on 2019-11-23 07:13

from django.db import migrations, models
import django.db.models.deletion
import student_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_data', models.ImageField(upload_to=student_info.models.FaceImages.path_and_rename)),
                ('images_name', models.CharField(max_length=20)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_info.Student')),
            ],
        ),
    ]
